{
 "title": "NSQ Instances",
 "tags": [ "nsq-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(nsq_topic_message_count, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nsq_topic_message_count{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "topic",
    "query": {
     "query": "label_values(nsq_topic_message_count{job=~\"$job\",instance=~\"$instance\"},topic)"
    }
   },
   {
    "name": "channel",
    "query": {
     "query": "label_values(nsq_channel_message_count{job=~\"$job\",instance=~\"$instance\",topic=~\"$topic\"},channel)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Topics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$topic topic end-to-end processing time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by (instance) (nsq_topic_e2e_latency_99_percentile{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\"})",
     "legendFormat": "{{ instance }} p99"
    }
   ]
  },
  {
   "title": "$topic topic messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg by (instance) (rate(nsq_topic_message_count{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\"}[$__rate_interval]))",
     "legendFormat": "{{ instance }} rps"
    }
   ]
  },
  {
   "title": "$topic topic depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (nsq_topic_depth{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\"})",
     "legendFormat": "{{ instance }} depth"
    },
    {
     "expr": "sum by (instance) (nsq_topic_backend_depth{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\"})",
     "legendFormat": "{{ instance }} memory+disk depth"
    }
   ]
  },
  { "title": "Channels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "$channel channel end-to-end processing time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by (instance) (nsq_channel_e2e_latency_99p{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\",channel=~\"$channel\"})",
     "legendFormat": "{{ instance }} p99"
    }
   ]
  },
  {
   "title": "$channel channel clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (instance) (nsq_channel_client_count{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\",channel=~\"$channel\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$channel channel stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (nsq_channel_depth{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\",channel=~\"$channel\"})",
     "legendFormat": "{{ instance }} depth"
    },
    {
     "expr": "sum by (instance) (nsq_channel_backend_depth{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\",channel=~\"$channel\"})",
     "legendFormat": "{{ instance }} memory+disk depth"
    },
    {
     "expr": "sum by (instance) (nsq_channel_in_flight_count{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\",channel=~\"$channel\"})",
     "legendFormat": "{{ instance }} in-flight"
    },
    {
     "expr": "avg by (instance) (rate(nsq_channel_requeue_count{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\",channel=~\"$channel\"}[$__rate_interval]))",
     "legendFormat": "{{ instance }} requeue"
    },
    {
     "expr": "avg by (instance) (rate(nsq_channel_timeout_count{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\",channel=~\"$channel\"}[$__rate_interval]))",
     "legendFormat": "{{ instance }} timeout"
    },
    {
     "expr": "sum by (instance) (nsq_channel_deferred_count{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\",channel=~\"$channel\"})",
     "legendFormat": "{{ instance }} deferred"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Heap memory (avg)",
   "type": "timeseries",
   "description": "Average memory usage if instance=All filter is selected",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (job) (nsq_mem_heap_in_use_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "heap in use"
    },
    {
     "expr": "avg by (job) (nsq_mem_heap_idle_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "heap idle bytes"
    },
    {
     "expr": "avg by (job) (nsq_mem_heap_released_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "heap bytes released"
    }
   ]
  },
  {
   "title": "Heap objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nsq_mem_heap_objects{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Next GC in bytes",
   "type": "timeseries",
   "description": "The number used bytes at which the runtime plans to perform the next garbage collection",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nsq_mem_next_gc_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "GC pause time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "nsq_mem_gc_pause_usec_99{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "p99 {{ instance }}"
    }
   ]
  }
 ]
}